### ISSUE TITLE
data weaving as interface short piece

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/startwords#112]
The idea: use the deepzoom image of the weaving as a way to browse the references using data from the Derrida's Margins site. (Since we can't do it with the physical object, I thought we could simulate our idea with the image).

Approach: use seadragon with constraints on zoom/drag (currently: no zoom in/out allowed, only allows scrolling horizontally; default zoom needs to be adjusted based on screen size).

I've added my preliminary/experimental code for the data weaving deep zoom image as a short piece.  It still needs at least the following for minimum functionality:

- resolve CORS issue so we can display reference cards from the Derrida's Margins site
- styles for reference cards on this site (may be able to borrow/adapt from Derrida's Margins site styles)
- a different layout that works for mobile 
- hide reference card on touch event
- correct default zoom size & position for different screens
- positions for page numbers and references on the weaving (first few were manually added)

The current styles for the annotation zones are placeholders, to test layout.

The code needs to be cleaned up quite a bit; it would be cool if there's a way to refactor to use our existing seadragon shortcode (but not sure how we can pass in all the options we need).

## todos and ideas based on 9/1 conversation with Gissoo
- [x] most important: test if we can trigger startwords contextual notes from the reference zones in the deep zoom
- [x] use seadragaon navigator to give overview
- [x] if we can use contextual notes, use gray instead of purple (see example in figma designs)
- [x] try red outlines for the reference zones; they should probably be always shown on mobile
- [x] ~possibly:~ implement dark mode color styles (Gissoo will look at this)
- [x] can we use web annotation / simple annotation to draw the zones we want to use for the viewer? (instead of calculating manually)
- [x] add zones for all references in the weaving
- [x] add zones for pages
- [x] load reference zones into viewer from data file
- [x] generate notes for references included in the weaving
- [x] disable scroll when positioning contextual note
- [x] position contextual note better vertically
- [x] numbers under zones should be full opacity
- [x] disable back link in notes
- [x] fix or remove broken images
- [x] link to books on derrida's margins site 
- [x] add numbers to annotated zones
- [x] set default zoom level based on screen size
- [x] style links in contextual notes
- ~possibly: allow zoom in/out but with different controls~
- ~possibly: could we let users choose which way they want to view it? vertical/horizontal; if we do, can we track what they choose?~

**Comment by rlskoeser** [comment]
@gissoo as we discussed, I've put my experiment with the deep zoom of the data weaving on the site so you can look at it and think about how to approach it.

Here's the preliminary version:
https://startwords.cdh.princeton.edu/issues/1/weaving-as-interface/

Here in the code is where the overlays for page number and reference block are currently defined: 
https://github.com/Princeton-CDH/startwords/blob/master/content/issues/1/dataweaving-zoom.html#L114-L203 

I _think_ the sizes are relative to the original, but I didn't actually confirm. They don't need to be structured the way I have them; it would be better to load them from a data file.

**Comment by rlskoeser** [comment]
OK, @gissoo — I have made some changes to my prototype and have a rough proof-of-concept showing I can indeed trigger a contextual note when a deep-zoom overlay region is clicked. 

![Screen Shot 2020-09-09 at 4 40 19 PM](https://user-images.githubusercontent.com/691231/92652568-2e6e2d00-f2bb-11ea-8ca6-bfc2782100ef.png)

It looks like it is functional on mobile also (obviously we'll need to adjust the styles so content will fit better...)

![Screen Shot 2020-09-09 at 4 42 15 PM](https://user-images.githubusercontent.com/691231/92652880-8d33a680-f2bb-11ea-9a75-51a216b6cac7.png)

**Comment by gissoo** [comment]
@rlskoeser thank you!!! This is amazing, so glad we can do this!!

**Comment by gissoo** [comment]
@rlskoeser I finally have some things to show: 
[Please look here](https://www.figma.com/file/MEt3gfKX4N3WTLPbLGBbGC/Startwords?node-id=1155%3A7350) – zoom out as it will probably be too zoomed in

In the designs, you can see: 
- default view of the weaving image, including how zoomed in it should be. I prefer the ones that are already zoomed in, where page numbers and a polygon are already showing and ready to be interacted with, because that makes it easier to begin interaction. I would recommend we show polygons with 50% transparency on default view. 

- selected view for desktop, tablet, and mobile with the contextual note container. I think as long as the note container appears at the bottom of the weaving it's fine, preferably in the center of the page. 
- I have experimented with full-width vs. the standard image sizes (the dimensions we have already agreed on)

- some ways that aim to improve the experience of zooming in and out. I prefer "zooming - v3" – or what [they are doing here](http://ignitersworld.com/lab/imageViewer.html) – I find it really easy to control. I would strongly suggest that we do not zoom in and out by clicking/tapping or scrolling on the image, it makes the experience very poor and unreliable. can we use a slide bar to zoom in and out instead of the + - buttons?

- experiments with image width. I'm thinking "what if we make the weaving image container full width here? I know it’s not consistent with our image styles, but this is different, the weaving image is the most important part of this page." – both versions are there 

Another comment:
- moving through the weaving by dragging the image left and right is great.   


Please let me know your thoughts.

**Comment by gissoo** [comment]
@rlskoeser I know you said this is still in progress, however just two points that I realized: 
1. could we make the image container wider so that the numbers both above and below it would be visible? Or just make sure those are visible by default some way? 
2. Could the numbers at the bottom have no transparency? It would be much better if they are always 100% visible.

**Comment by rlskoeser** [comment]
@gissoo thank you!

1. This is one of the things on my list! I need to set the default zoom level based on screen size but I haven't had the chance to figure that out yet! It's tricky because of the different screen sizes. This is the thing that I would like to look at with you.
2. Yes, I wanted them to be fully visible and couldn't figure out how! They seemed to not let me override the transparency of the object they belong to. I'll add it to my list and see if can find a solution.

**Comment by gissoo** [comment]
@rlskoeser I'm noticing that the annotations and the image container function properly and can be viewed on Chrome desktop. 

- On firefox desktop when I hold the container and push it to the left to see more of the weaving once I release my finger it slightly zooms in which causes the numbers at the bottom to not be visible, and I can’t zoom out. Even clicking inside the container causes the same thing to happen. If clicking the top region within the container the bottom part gets cut out, if clicking the bottom region the top part gets cut out – NOTE: This only happens when the window is in full screen mode in FF. 
![Screen Shot 2020-10-26 at 4 23 57 PM](https://user-images.githubusercontent.com/44615389/97224574-b8a91c80-17a7-11eb-8517-8c78cf390f98.png)

![Screen Shot 2020-10-26 at 4 24 13 PM](https://user-images.githubusercontent.com/44615389/97224583-bc3ca380-17a7-11eb-9fac-e1b1d95ce93f.png)


- On Safari desktop nothing shows up in the image container. 
<img width="1680" alt="Screen Shot 2020-10-26 at 4 23 44 PM" src="https://user-images.githubusercontent.com/44615389/97224697-e7bf8e00-17a7-11eb-86b7-f4416fbc9d5b.png">

**Comment by gissoo** [comment]
@rlskoeser Tested again on mobile(iOS), and weirdly the weaving image doesn't appear in any of the browsers Safari, Chrome, and FireFox, only the small viewer shows up

**Comment by gissoo** [comment]
@rlskoeser ok I feel bad to keep overloading you right now, but just noticed that none of the mobile browsers (iOS) show the "X"/close button in contextual notes (I think only one did).

**Comment by rlskoeser** [comment]
@gissoo the browsers where the weaving image wasn't appearing was a javascript compatibility problem, which @thatbudakguy took care of — please do any further testing on https://startwords.cdh.princeton.edu/issues/1/weaving-as-interface/

I couldn't replicate your problem exactly, but a couple of thoughts:
- I might need to adjust how much we zoom after fitting vertically depending on the screen size (was hoping to avoid having to customize it!)
- I have logic that re-adjusts the zoom level when you resize the window, maybe that is triggering when it shouldn't? I could disable if that's preferable

I noticed on mobile that I can pinch to zoom — I thought I had disabled this, but I guess I only disabled some of the other ways you can zoom (click and scroll?).

**Comment by rlskoeser** [comment]
> @rlskoeser ok I feel bad to keep overloading you right now, but just noticed that none of the mobile browsers (iOS) show the "X"/close button in contextual notes (I think only one did).

@gissoo on this page or on all of them? (it's working on android)

**Comment by gwijthoff** [comment]
@gissoo @rlskoeser dang I'm seeing the same thing on iOS Safari and FF. No "close" icon.

![IMG_BEB833898A8C-1](https://user-images.githubusercontent.com/5580840/97229324-92d34600-17ae-11eb-86c9-935522eca6d1.jpeg)

**Comment by gissoo** [comment]
@rlskoeser I was testing with the 

> @gissoo the browsers where the weaving image wasn't appearing was a javascript compatibility problem, which @thatbudakguy took care of — please do any further testing on https://startwords.cdh.princeton.edu/issues/1/weaving-as-interface/
> 

- That's where I have been testing! iOS pages are all fine now, they all show up! 

> I couldn't replicate your problem exactly, but a couple of thoughts:
> 

- the problem I mentioned with the container zoom level I just learned it only happens when I have the browser on full screen mode on the DELL monitor (all browsers)!!!! :O (so not on my desktop)

>     * I might need to adjust how much we zoom after fitting vertically depending on the screen size (was hoping to avoid having to customize it!)
> 
>     * I have logic that re-adjusts the zoom level when you resize the window, maybe that is triggering when it shouldn't? I could disable if that's preferable
> 

- thank you!!! to your second point, I refreshed the window when I viewed it on full screen mode. Maybe that is what it is, I'm not sure. What would happen if you disable it?


> I noticed on mobile that I can pinch to zoom — I thought I had disabled this, but I guess I only disabled some of the other ways you can zoom (click and scroll?).
> 

- OMG!! It just worked for me! That is awesome!!!!

**Comment by gissoo** [comment]
> > @rlskoeser ok I feel bad to keep overloading you right now, but just noticed that none of the mobile browsers (iOS) show the "X"/close button in contextual notes (I think only one did).
> 
> @gissoo on this page or on all of them? (it's working on android)

- I've only been testing this particular page – didn't check the other pages, just checked now one article on one browser and it's fine there!

**Comment by gissoo** [comment]
> @gissoo @rlskoeser dang I'm seeing the same thing on iOS Safari and FF. No "close" icon.
> 
> ![IMG_BEB833898A8C-1](https://user-images.githubusercontent.com/5580840/97229324-92d34600-17ae-11eb-86c9-935522eca6d1.jpeg)

for me it's also chrome in addition to the other two.

**Comment by rlskoeser** [comment]
I was hoping it was related to a dark model style, I just pushed a change that I hoped would fix it, but I'm not sure it did.

**Comment by gwijthoff** [comment]
@rlskoeser looks like it did?

![IMG_9A67A0FB70FD-1](https://user-images.githubusercontent.com/5580840/97230363-2eb18180-17b0-11eb-9803-3459e7b4aceb.jpeg)

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff It's back on Chrome and Firefox!!! Not on Safari though

**Comment by rlskoeser** [comment]
The x is displaying for me on _one_ (and only one) of the contextual notes in Safari. Not sure what that means or how it could happen...

**Comment by gissoo** [comment]
> The x is displaying for me on _one_ (and only one) of the contextual notes in Safari. Not sure what that means or how it could happen...

- This was exactly my experience earlier, and now it's displaying on two :D

**Comment by rlskoeser** [comment]
@gissoo @gwijthoff I checked this morning and the x is displaying on safari on my ipad after a reload – I think maybe it had just cached the previous version and wasn't getting the fix. If one of you can confirm, can we go ahead and close this issue?

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff I also just tested few minutes ago and was about to write!! It's fixed for me too!
