### ISSUE TITLE
Issue 2 misc to-do's

### ISSUE THREAD

**Issue by gwijthoff** [Princeton-CDH/startwords#195]
- [x] #196
- [x] in PDF: page break after header / article metadata
- [x] in PDF: footnote numbers are duplicated, 11, 22, 33, etc
- [x] in PDF: keyboards, tweets, and videos have some display issues
- [x] in PDF: H2 headings create page breaks in all PDFs
- [x] in TXT: header ASCII art scrambled -- we think this will be resolved when publishing on GH Pages
- [x] in TXT: need a line break after metadata block and article text
- [x] Keyboards
    - [x] in PDF: add descriptive text about interactive elements: "The online version of this essay includes interactive keyboards threaded throughout the text."
    - [x] fix typos and format notes in keyboard interludes
    - [x] in PDF: fix extra vertical space for embedded keyboards
- [x] Serendipity
    - [x] TXT output includes both alt text and the embed code for the video
    - [x] TXT encoding doesn't work for Hebrew characters
    - [x] PDF replace video with alt still image and note about video
- [x] Douglass
    - [x] no TXT output for Tweets
    - [x] no TXT output for videos
    - [x] PDF replace youtube videos with alt still image and note about video (custom youtube shortcode?)
- [x] #197
- [x] generate PDFs for all four pieces for review by authors
- [x] one of the pull quotes on Data's Destinations is doing that funky page boundary thing we dealt with on RMs essay

**Comment by kmcelwee** [comment]
@rlskoeser @gwijthoff I believe this can be closed
